version: "3.1"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8080"

  db:
    image: mariadb:latest
    environment:
      MARIADB_USER: user
      MARIADB_PASSWORD: my-cool-secret
      MARIADB_ROOT_PASSWORD: my-secret-password

# If used from a local clone, this will automatically initialize the database
#    volumes:
#      - ./test.sql:/docker-entrypoint-initdb.d/test.sql

  admin:
    image: phpmyadmin:latest
    ports:
      - "8083:80"
    environment:
      PMA_HOST: db
